repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt
        language: system
        args: [-w]
        files: \.go$

      - id: go-vet
        name: go vet
        entry: go vet
        language: system
        pass_filenames: false
        args: [./...]

      - id: go-test
        name: go test
        entry: go test
        language: system
        pass_filenames: false
        args: [./...]

      - id: gosec
        name: gosec security scan
        entry: gosec
        language: system
        pass_filenames: false
        args: [./...]

      - id: govulncheck
        name: govulncheck
        entry: govulncheck
        language: system
        pass_filenames: false
        args: [./...]
