services:
  docstore-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: docstore-api
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/documents"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - docstore-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: docstore-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../ssl:/etc/nginx/ssl:ro
    depends_on:
      - docstore-api
    restart: unless-stopped
    networks:
      - docstore-network
    profiles:
      - production

networks:
  docstore-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  docstore-data:
    driver: local