services:
  docstore-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: docstore-api-prod
    ports:
      - "8080:8080"
    env_file:
      - ../config/.env.production
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/auth/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - docstore-network
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Production reverse proxy
  nginx:
    image: nginx:alpine
    container_name: docstore-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ../ssl:/etc/nginx/ssl:ro
    depends_on:
      - docstore-api
    restart: unless-stopped
    networks:
      - docstore-network

networks:
  docstore-network:
    driver: bridge

volumes:
  docstore-data:
    driver: local