global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # DocStore API metrics endpoint
  - job_name: 'docstore-api'
    static_configs:
      - targets: ['docstore-api-prod:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # DocStore API health endpoint (removed - health checks should not be scraped as metrics)
  # Use /metrics endpoint for Prometheus metrics instead

  # Docker daemon metrics (if enabled)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
