// Package main provides the Document Store API
// @title Hornetsecurity-Document Store API
// @version 1.0
// @description A simple document storage API with CRUD operations and JWT authentication
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.
package main

import (
	"log"

	"docstore-api/src/config"
	"docstore-api/src/controllers"
	_ "docstore-api/src/docs" // This will be generated by swag
	"docstore-api/src/middleware"
	"docstore-api/src/models"
	"docstore-api/src/services"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	// Load configuration
	cfg := config.LoadConfig()

	// Log the detected environment
	log.Printf("Detected environment: %s", cfg.Environment)

	// Create layers: Model -> Service -> Controller
	store := models.NewDocumentStore()
	documentService := services.NewDocumentService(store)
	documentController := controllers.NewDocumentController(documentService)
	authController := controllers.NewAuthController(cfg)
	healthController := controllers.NewHealthController(cfg)

	// Setup Gin router based on environment
	if cfg.Environment == "production" {
		gin.SetMode(gin.ReleaseMode)
	}
	r := gin.Default()

	// Configure CORS middleware if enabled
	if cfg.EnableCORS {
		corsConfig := cors.DefaultConfig()

		// Use custom origins if provided, otherwise use defaults
		if len(cfg.CORSOrigins) > 0 {
			corsConfig.AllowOrigins = cfg.CORSOrigins
			log.Printf("CORS middleware enabled with custom origins: %v", cfg.CORSOrigins)
		} else if cfg.Environment == "production" {
			// Production: Allow common origins until domain is configured
			// TODO: Update with your production domain when available
			corsConfig.AllowOrigins = []string{
				"https://localhost",
				"https://127.0.0.1",
				"http://localhost:8080",
				"https://localhost:8080",
			}
			log.Printf("CORS middleware enabled for production with default origins (update CORS_ORIGINS when domain is ready)")
		} else {
			// Development: Allow localhost for Swagger UI
			corsConfig.AllowOrigins = []string{
				"http://localhost:8080",
				"https://localhost:8080",
				"http://127.0.0.1:8080",
				"https://127.0.0.1:8080",
			}
			log.Printf("CORS middleware enabled for development")
		}

		corsConfig.AllowMethods = []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"}
		corsConfig.AllowHeaders = []string{"Origin", "Content-Length", "Content-Type", "Authorization"}
		corsConfig.AllowCredentials = true
		r.Use(cors.New(corsConfig))
	} else {
		log.Printf("CORS middleware disabled")
	}

	// Health check endpoint (no authentication required)
	r.GET("/health", healthController.HealthCheck)
	log.Printf("Health check endpoint registered at: /health")

	// Metrics endpoint for Prometheus (no authentication required)
	r.GET("/metrics", healthController.Metrics)
	log.Printf("Metrics endpoint registered at: /metrics")

	// API routes
	v1 := r.Group("/api/v1")
	{
		// Auth routes (no JWT required)
		auth := v1.Group("/auth")
		{
			auth.POST("/login", authController.Login)
		}

		// Protected document routes (JWT required)
		documents := v1.Group("/documents")
		documents.Use(middleware.JWTAuthMiddleware(cfg))
		{
			documents.POST("", documentController.CreateDocument)
			documents.GET("", documentController.ListDocuments)
			documents.GET("/:id", documentController.GetDocument)
			documents.PUT("/:id", documentController.UpdateDocument)
			documents.PATCH("/:id", documentController.PartialUpdateDocument)
			documents.DELETE("/:id", documentController.DeleteDocument)
		}
	}

	// Environment-specific Swagger endpoint
	if cfg.Environment == "production" {
		// Production Swagger with instance name
		r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, ginSwagger.InstanceName("prod")))
	} else {
		// Development Swagger with instance name
		r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, ginSwagger.InstanceName("dev")))
	}

	// Add some sample data
	sampleDocs := []models.Document{
		{
			ID:          "1",
			Name:        "Getting Started",
			Description: "A guide to getting started with the document store",
		},
		{
			ID:          "2",
			Name:        "API Reference",
			Description: "Complete API reference for document operations",
		},
	}

	for _, doc := range sampleDocs {
		if err := store.Create(doc); err != nil {
			log.Printf("Error creating sample document %s: %v", doc.ID, err)
		}
	}

	// Start server with HTTPS or HTTP based on configuration
	if cfg.EnableHTTPS {
		log.Printf("Starting HTTPS server on :%s", cfg.ServerPort)
		log.Printf("Using cert file: %s, key file: %s", cfg.CertFile, cfg.KeyFile)
		log.Printf("Swagger UI available at: https://localhost:%s/swagger/index.html", cfg.ServerPort)

		if err := r.RunTLS(":"+cfg.ServerPort, cfg.CertFile, cfg.KeyFile); err != nil {
			log.Fatal("Failed to start HTTPS server:", err)
		}
	} else {
		log.Printf("Starting HTTP server on :%s", cfg.ServerPort)
		log.Printf("Swagger UI available at: http://localhost:%s/swagger/index.html", cfg.ServerPort)

		if err := r.Run(":" + cfg.ServerPort); err != nil {
			log.Fatal("Failed to start HTTP server:", err)
		}
	}
}
